# Generated by Django 5.2.11 on 2026-02-20 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=500, null=True, unique=True)),
                ('is_confirmed', models.BooleanField(blank=True, default=None, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='unique_slug_index')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='unique_slug_constraint')],
            },
        ),
    ]
