# Generated by Django 5.2.11 on 2026-02-20 23:41

from django.db import migrations

from scripts.slugify_attendees import INVITEES_LIST, get_cleaned_invitees_list

def create_initial_confirmations(apps, schema_editor):
    confirmation_model = apps.get_model('confirmation', 'Confirmation')
    cleaned_invitees = get_cleaned_invitees_list(INVITEES_LIST)
    for slug in cleaned_invitees:
        confirmation_model.objects.get_or_create(slug=slug)

def delete_initial_confirmations(apps, schema_editor):
    confirmation_model = apps.get_model('confirmation', 'Confirmation')
    cleaned_invitees = get_cleaned_invitees_list(INVITEES_LIST)
    confirmation_model.objects.filter(slug__in=cleaned_invitees).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_confirmations, delete_initial_confirmations),
    ]
