# Generated by Django 5.2.11 on 2026-03-28 14:41

from django.db import migrations, models
from scripts.slugify_attendees import get_full_invitee_mapping


def update_names_confirmations(apps, schema_editor):
    confirmation_model = apps.get_model('confirmation', 'Confirmation')
    cleaned_invitees = get_full_invitee_mapping()
    for slug, name in cleaned_invitees.items():
        invitee, created = confirmation_model.objects.get_or_create(slug=slug)
        if created:
            print(f"Created confirmation for slug: {slug}")
        else:
            print(f"Confirmation already exists for slug: {slug}")
        invitee.name = name
        invitee.save()


def remove_names_confirmation(apps, schema_editor):
    confirmation_model = apps.get_model('confirmation', 'Confirmation')
    confirmation_model.objects.all().update(name=None)


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0002_auto_20260220_2341'),
    ]


    operations = [
        migrations.AddField('Confirmation', 'name', models.CharField(max_length=255, null=True)),
        migrations.RunPython(update_names_confirmations, remove_names_confirmation),
    ]
